<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{fb865085-101d-43b2-9288-aeafc8caefc8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	wing : BOOL;
	cash : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[wing := cash;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>