<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Lamp" Id="{6ff10d14-b38e-48d3-97d9-6388932f2332}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Lamp
VAR
	counter11 : int;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[counter11 := counter11 + 1;]]></ST>
    </Implementation>
    <LineIds Name="Lamp">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>