<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Light" Id="{a197e08d-140c-45b4-9184-3218b9679aed}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Light
VAR
	counter : int;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[counter := counter + 1;
]]></ST>
    </Implementation>
    <LineIds Name="Light">
      <LineId Id="5" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>